# Generated by Django 5.2 on 2026-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
